### ISSUE TITLE
[Feature request] keep tree-style-tab-for-chrome static / visible all time (disable autohide)

### ISSUE THREAD

**Issue by stefan123t** [Suibs/Tree-Style-Tab-For-Chrome#1]
Dear Suibin Hong,
being a long time user of tree-style-tabs from piroo on Firefox I have been looking for an alternative on Google Chrome for years.
Sidewise extension is not an option as it always keeps the tabs in a separate window.
So your new implementation is the closest I have seen in several years, despite the fact that I am used to have the tree visible at all the times. Only rarely (eg. for screenshots) I do hide the tree.
Is it possible to keep the tab list visible all the times as a feature request ?
Also note that I have multiple monitors installed and having the chrome window on the right hand screen makes it difficult to toggle the tree visible, being the cross-boundary between my two screens.
Kind regards,
Stefan

**Comment by Suibs** [comment]
Hi Stefan,

Thank you for reaching out! I'm very much aware of the issue you've addressed as I was a previous user of TST from piroo too and it's the reason of how this project came to be. I'd like to note that: having a permanent inline menu is one of the top features to come in the next build which will be ready before end of this week. 

Many thanks,
Suibin

**Comment by stefan123t** [comment]
Hi Suibin,
just let me know when the release is ready, so I can take a look at the build.
Do you need feedback from tests ?
Kind regards,
Stefan

**Comment by Suibs** [comment]
Hi Stephen,

Will do! Can you clarify what you mean by tests?

Many thanks,
Suibin

**Comment by Suibs** [comment]
Dear Stephen,

Due to the limitation of the lack of sidebar API from chrome. I've decided not to implement the push menu option as it will end up being a broken feature that only works for some sites. Keep in mind that option to toggle which side to have the menu will be available. Hope that helps! 

Many thanks,
Suibin

**Comment by Suibs** [comment]
Dear Stephen,

I'm currently considering adopting the "tabs outliner" approach in creating an external window as an extra feature to have that will accommodate the application to be always active. What's your take on the solution? An example [image]([http://tiny.cc/sy34oz](image)), that illustrates what I want to implement.

Kind regards,
Suibin

**Comment by stefan123t** [comment]
Dear Suibin,
that is the reason I am still sticking with FF and TST as handling two separate windows on my Desktop env is not an option for me (ie. too complicated).
I believe sidewise also took this route some years ago with no success for me see above.
I also found that the sidebar from your plugin does not appear when touching left side of the window, which seems related to the site being displayed. I have seen this with an internal application until now only so I can not reproduce it on the public internet yet.
Kind regards,
Stefan

**Comment by rfrelow83** [comment]
The external window approach sounds great to me! Would definitely get great use out of that!

Thanks!

**Comment by Suibs** [comment]
Dear Stefan,

Although it's a shame that the current build isn't suitable for your needs, still appreciate the feedback so much! 

Kind regards,
Suibin

**Comment by Suibs** [comment]
> The external window approach sounds great to me! Would definitely get great use out of that!
> 
> Thanks!

Should expect the external mode to be available in the next 2 weeks or so. Thanks for tuning in @rfrelow83!

**Comment by Suibs** [comment]
Just a quick update, external mode is currently being worked on and should be available before the end of the week! You can see the project's progress here if you're interested: https://trello.com/b/u9Mjyu8s/tree-style-tab-for-google-chrome-roadmap
Thanks! 👍
