### ISSUE TITLE
Shortcut to toggle extension on/off

### ISSUE THREAD

**Issue by Fedolodic** [Suibs/Tree-Style-Tab-For-Chrome#10]
I use dual monitors and when I have two instances of chrome running on each monitor, I always inadvertently activate the extension when navigating between each monitor. It would be great to see a toggle on/off feature or a shortcut to show/hide the extension.

**Comment by Suibs** [comment]
Hi @Fedolodic, thank you for your feedback. Have you tried changing the side of the menu to be shown (menu alignment in settings) from such that you don't run into activating the menu when switching monitor?

**Comment by Fedolodic** [comment]
Hi @Suibs thanks for the quick response! Yes, I've tried changing the menu alignment, but let me be more thorough with my problem:

Case 1: Menu is aligned on the left
    When I'm navigating from the right window to the left, the right window triggers the left menu 
    and obscures my work.

Case 2: Menu is aligned on the right
    When I'm navigating from the left window to the right, the left window triggers the right menu 
    and obscures my work.

Changing the overlay is a quick fix, but sometimes the menu itself is covering areas of the screen that I'm focusing on. In addition, resizing the menu seems to trigger a min-width, which sometimes is not enough to let me clearly see my work.

**Comment by Suibs** [comment]
@Fedolodic thank you! I understand your difficulties now and fortunately, in the next patch, external popup window menu will be available which should be the solution to your current issue. Furthermore, are you requesting for a smaller min-width for the menu resize in regards to your last point?

**Comment by Fedolodic** [comment]
@Suibs Thanks! I think the external popup window should give me a solution. Because of this, I'm not requesting smaller-min width. That said, if you decide on adding that functionally, it'll be a nice cherry on top 🍒.

**Comment by Suibs** [comment]
Hi @Fedolodic, the release for the external popup window took place yesterday. Would love to know what you think about it! :)

**Comment by Fedolodic** [comment]
@Suibs I think it's great! I get all the functionality of Tree Style without it interfering with the edges of my screen! One note though, and I'm just griping here, when I'm in fullscreen mode and I click the Tree Style extension I expected a popup window similar to Wappalyzer, Stylish or Noisli. This pop style lets me stay in my current window without moving my screen completely. In any case, thanks for adding in this new feature 👍

**Comment by Suibs** [comment]
Hey @Fedolodic, glad you liked the update! When you're in full screen mode, if you have removed all the pop-up tree style tab windows or if you toggled off the pop-up mode, you'll find yourself access to the original inline menu which can be opened from a hover on the side of the browser. Hope that helps, thanks!
