### ISSUE TITLE
Please add a pin button so the side tab doesn't disappear.

### ISSUE THREAD

**Issue by bassamanator** [Suibs/Tree-Style-Tab-For-Chrome#4]
Nice little tool. I just would like for it to stay put and not disappear.

Thanks.

**Comment by Suibs** [comment]
Thank you! You may like what's on the latest of the in-progress item! 
![image](https://user-images.githubusercontent.com/23139754/82765390-794c5d80-9e0e-11ea-8496-085b2fd0a3e1.png)
You can stay up to date with the latest progress of the project via the [https://trello.com/b/u9Mjyu8s/tree-style-tab-for-google-chrome-roadmap](trello) board too!

**Comment by Suibs** [comment]
Thank you! You may like what's on the latest in-progress list! 
![image](https://user-images.githubusercontent.com/23139754/82765390-794c5d80-9e0e-11ea-8496-085b2fd0a3e1.png)
You can stay up to date with the latest progress of the project via the trello board too! Link: [https://trello.com/b/u9Mjyu8s/tree-style-tab-for-google-chrome-roadmap](url)
