### ISSUE TITLE
Issues with Ublock Origin

### ISSUE THREAD

**Issue by anishmittal2020** [Suibs/Tree-Style-Tab-For-Chrome#5]
When Tree- Style tab extension is enabled Ublock list of trackers for every tab shows trackers from other tabs as well! See below:

![image](https://user-images.githubusercontent.com/18417820/82764718-2fb14200-9e11-11ea-810e-692391ebfe54.png)

On the same website when the extension is disabled we get the reduced number of trackers and only from that particular tab as follows:

![image](https://user-images.githubusercontent.com/18417820/82764756-80289f80-9e11-11ea-9b7e-0c6d5f764a36.png)

**Comment by Suibs** [comment]
Thank you! Looking into it now

**Comment by Suibs** [comment]
Hi Anish, 

I was unable to replicate the same result, does the same happen for other tab for you as well? 

Kind regards

Suibin

**Comment by anishmittal2020** [comment]
With your extenion: 

![image](https://user-images.githubusercontent.com/42092626/82765161-9126e000-9e14-11ea-8d4f-8300efe801e5.png)

Without your extenion: 

![image](https://user-images.githubusercontent.com/42092626/82765172-a3088300-9e14-11ea-93db-89d0a73dccfe.png)

**Comment by Suibs** [comment]
Hi Anish, 

I've investigated and found the root cause. Each of the request for the favicon of each of the tab that exists in the extension. The best evidence for that is when uBlock extension has blocked all those requests, there is no favicon shown for any of the tab, as shown below:
![image](https://user-images.githubusercontent.com/23139754/82765311-96346100-9e0d-11ea-9785-09e738a911d1.png)
Without uBlock origin blocking the sites:
![image](https://user-images.githubusercontent.com/23139754/82765319-b06e3f00-9e0d-11ea-91a7-cd7d079b9312.png)

Kind regards
Suibin

**Comment by anishmittal2020** [comment]
Hi Suibin

Yes all favicons are available when we disable 3rd party. 

![image](https://user-images.githubusercontent.com/42092626/82765479-933e6e00-9e17-11ea-85c2-86082f64e32e.png)

But the issue is for advanced users they have to frequently allow certains CDNs and websites as their default settings blow every third party website. This becomes tedious and difficult when our list of disabled website for every tab gets populated by information from other tabs.

**Comment by Suibs** [comment]
Hi Anish,

Totally onboard with your concerns, I've noted down the solution in the roadmap. The link for it is: https://trello.com/b/u9Mjyu8s/tree-style-tab-for-google-chrome-roadmap

Kind regards
Suibin

**Comment by anishmittal2020** [comment]
Hi Suibin

I am not sure but I think the issue is resolved by you or it was updated in the trello board that you shared. But I was unsuccessful in locating the issue on the trello board.

**Comment by Suibs** [comment]
Hi Anish,

I've attached the card with this post for reference:

![image](https://user-images.githubusercontent.com/23139754/83029728-ea685c80-a02a-11ea-9e8c-2fea67918210.png)


kind regards
