### ISSUE TITLE
[Issue] With The Great Suspender extension.

### ISSUE THREAD

**Issue by Lavnesh** [Suibs/Tree-Style-Tab-For-Chrome#6]
Tree Style Tab for chrome (0.0.3) is not working if tab is suspended by The Great Suspender(7.1.0). From that tab if you trying to access Tree Style Tab.

[The Great Suspender](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg?hl=en) extension.

**Tree Style Tab: Setting**
![image](https://user-images.githubusercontent.com/65883813/82780916-2908e600-9e76-11ea-8796-70347ca0a2bb.png)

**The Great Suspender: Setting**
![image](https://user-images.githubusercontent.com/65883813/82780955-45a51e00-9e76-11ea-937a-eb19aa6f4272.png)
![image](https://user-images.githubusercontent.com/65883813/82781010-61102900-9e76-11ea-8452-0846f81f3862.png)

**Comment by Suibs** [comment]
Hi @Lavnesh, this has been a known issue and had been created as a to-do for the future iterations. You can find out more about it and the progress of the project here: https://trello.com/b/u9Mjyu8s/tree-style-tab-for-google-chrome-roadmap
Thank you!
