### ISSUE TITLE
[Feature Enhancement] Close option and width.

### ISSUE THREAD

**Issue by Lavnesh** [Suibs/Tree-Style-Tab-For-Chrome#7]
In this I am talking about 2 features enhancement. See pic 1st.

![image](https://user-images.githubusercontent.com/65883813/82782261-8eaaa180-9e79-11ea-8f83-ecb5a6b5d329.png)

**1:** Close option **X** it should be in same line not in new line. Because of that we need to do more scrolling if there is large number of tabs. And I am assuming Tree-Style-Tab if for those guys who yous large number of tabs.

**2:** Provide option to change **width** of Tree-Style-Tab. Most of the time Initially header of web page is same and it confusing which one to select.

**Comment by Suibs** [comment]
Hi again @Lavnesh, first and foremost thank you for feedbacks! 
To address your queries:
1. Definitely, the cross by default should absolutely be inline with the tab. I've noted the issue down for investigation
2. Width resize is one of the current working feature and will be available in the next patch which is scheduled for review before the end of this week
