### ISSUE TITLE
zoom together with the page

### ISSUE THREAD

**Issue by SimFar** [Suibs/Tree-Style-Tab-For-Chrome#9]
the  tab tree displays in the same zoom level as the webpage. If the zoom level of the tree can be set independently. It would be great.

**Comment by Suibs** [comment]
Hi @SimFar, thanks for raising the issue! Your issue will be addressed in the new build (v0.0.5) in 2 weeks where external popup mode will be available. This means the application will be imbedded in a popup window independent of your webpage.
